### ISSUE TITLE
First file upload option not working

### ISSUE THREAD

**Issue by Rareitor** [GustavoASC/google-drive-vscode#12]
**Describe the bug**
The first option for uploading a file, that is selecting a specific file on workspace/folder in the explorer view, cannot find file.

**To Reproduce**
As shown in the README

**Expected behavior**
File uploaded, and a notification of such.

**Screenshots**
Error shown appears no matter what sort of file is tested, or where it is in the client computer:
![image](https://user-images.githubusercontent.com/25486736/99587294-e5bbaa00-29b6-11eb-95e5-87cee0cf5670.png)

**Please complete the following information:**
 - OS: Windows 10 2004
 - VSCode Version 1.51.5
 - Extension version 1.1.0

**Additional context**
Other 2 methods appear to work fine.

**Comment by GustavoASC** [comment]
Hello @Rareitor.
Thanks for opening this issue.

Yeah, it looks like this problem is only happening on Windows machines.
I've tested on a Linux (Ubuntu 20.04) machine and it worked fine, but on a Windows machine I get the exact same error.

I'll keep investigating this problem and let you know when the problem is solved.

**Comment by GustavoASC** [comment]
@Rareitor

I've just fixed it and published version 1.1.1 to MarketPlace.
Please update the extension on your VSCode and it will work fine :smile:
